### ISSUE TITLE
Cannot configure/connect to BC in Rails

### ISSUE THREAD

**Issue by aapis** [bigcommerce/bigcommerce-api-ruby#144]
### Expected behavior
```ruby
Bigcommerce.configure do |config|
  config.auth = 'legacy'
  config.url = ENV['BC_API_ENDPOINT_LEGACY']
  config.username = ENV['BC_USERNAME']
  config.api_key = ENV['BC_API_KEY']
end

puts Bigcommerce::System.time
#<Bigcommerce::System time=...>
```

### Actual behavior
https://www.dropbox.com/s/f2j2a53yu0zi30k/Screenshot%202017-05-03%2012.35.39.png?dl=0

Stack trace:
```
faraday (0.12.1) lib/faraday/options.rb:49:in `merge!'
faraday (0.12.1) lib/faraday/options.rb:60:in `merge'
faraday (0.12.1) lib/faraday/options.rb:52:in `block in merge!'
faraday (0.12.1) lib/faraday/options.rb:49:in `each'
faraday (0.12.1) lib/faraday/options.rb:49:in `merge!'
faraday (0.12.1) lib/faraday/options.rb:60:in `merge'
faraday (0.12.1) lib/faraday/connection.rb:61:in `initialize'
faraday (0.12.1) lib/faraday.rb:67:in `new'
faraday (0.12.1) lib/faraday.rb:67:in `new'
bigcommerce (1.0.0) lib/bigcommerce/connection.rb:11:in `build'
bigcommerce (1.0.0) lib/bigcommerce.rb:19:in `configure'
app/controllers/reviews_controller.rb:5:in `all'
actionpack (5.1.0) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.0) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.0) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.0) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.0) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.0) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.0) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.0) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.0) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.0) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.0) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.0) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.0) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.0) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.0) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.0) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.0) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.0) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.0) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.0) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.0) lib/action_dispatch/routing/route_set.rb:832:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.0) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.0) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.0) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.5.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.0) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.0) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.0) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.1.0) lib/rails/engine.rb:522:in `call'
puma (3.8.2) lib/puma/configuration.rb:224:in `call'
puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
puma (3.8.2) lib/puma/server.rb:435:in `process_client'
puma (3.8.2) lib/puma/server.rb:299:in `block in run'
puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

### Steps to reproduce behavior
1. Add BC_API_ENDPOINT_LEGACY, BC_USERNAME, BC_API_KEY to your bash profile.
2. Create a new controller in a rails application
3. Create a method in that controller.
4. Put the BigCommerce conf code in that method.
5. Navigate to the route/controller you created in a browser, see error message.

Maybe I'm missing a configuration step?

**Comment by aapis** [comment]
Not sure what I did but it is now printing `#<Bigcommerce::System time=1493846598>`, so it must have been a configuration error on my part.  Nevermind!
